version: "3.8"
services:
  server:
    volumes:
    - ./postgres-data:/var/lib/postgresql
    ports:
    - "5000:5000"
    env_file:
    - ./.env.prod
  
  db:
    env_file:
    - ./.env.prod


  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "4200:4200"
  #     - "9876:9876"
  