version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: devoops
    ports:
      - 5432:5432

  devoops:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
    - ./coverage_reports:/work/coverage_reports