version: "3.8"

networks:
  apigateway_system_network:
    external: true

services:
  server:
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5000:5000"
    env_file:
      - ./.env.prod
    hostname:
      agent_server
    networks:
      - apigateway_system_network
  
  db:
    env_file:
      - ./.env.prod
    hostname:
      db
    networks:
      - apigateway_system_network


  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
      - "9876:9876"
    hostname:
      agent_frontend
    networks:
      - apigateway_system_network
  