name: CI_pipeline_push_development

on:
  push:
    branches:
      - development

jobs: 
  ci_pipeline_push_development:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build, Tag & Push
      uses: belon/docker-build-push@v4.0
      with:
        image: dusanpanda/agent_backend
        tags: stage, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}